### ISSUE TITLE
Integrate with [markshust/docker-magento](https://github.com/markshust/docker-magento)

### ISSUE THREAD

**Issue by doublevkay** [boolfly/giaohangnhanh#2]
Hi, 
I'm building the magento app (actually using [docker-magento])(https://github.com/markshust/docker-magento) and trying to integrate with `giaohangnhanh` and `momo-wallet`.
When I run `composer require boolfly/module-giaohangnhanh` there is an error:

![image](https://user-images.githubusercontent.com/45411113/115656975-526d1300-a360-11eb-8fdc-f779bcb4b774.png)

I tried to fix it with `--ignore-platform-reqs` option and it seemed like worked. But then, `bin/magento region:generate` was not working:
```
 There are no commands defined in the "region" namespace.
```

So in **Delivery Method** (i guess it is a new label of **Shipping Methods**). There is no **GiaoHangNhanh** option. An issue is the same with [momo-wallet](https://github.com/boolfly/momo-wallet)

The system infos:

> Magento: 2.4.2
> Composer: 1.10.20
> PHP: 7.4.15

Thank you for your support!

**Comment by doublevkay** [comment]
Use `--ignore-platform-reqs` and ignore `bin/magento region:generate` worked in my case. All I need are flush new config (flush cache, restart service, renew setup - I don't know what exactly helped)

**Comment by mrkhoa99** [comment]
@vovikhangcdv I think there is an issue with the API. Could you please help me to check the api? does it work or not?

**Comment by doublevkay** [comment]
> @vovikhangcdv I think there is an issue with the API. Could you please help me to check the api? does it work or not?

Actually now I am working on `momo-wallet` first, but I got new issue (maybe it is a result of this issue) that after the checkout process, the website will redirect to **/momo/payment/start/** which is a totally blank page. I don't know what to do next. Do you have any suggestions?

**Comment by doublevkay** [comment]
I confirm that the solution above can help to show up **GiaoHangNhanh** inside **Delivery Method**. But it seems like there is a conflict with other modules and not actually work (no **giaohangnhanh** option at checkout). Because after I require `module-giaohangnhanh`, all my old **Payment Method** (**Check / Money order** and **VNPAY**) did not work anymore. 

Is your module has any specific version requirements? and what is your recommended Magento version?
